### ISSUE TITLE
INVALID COMMIT MSG: "refactor" is not allowed type !

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [bahmutov/simple-commit-message#11]
According to the image below, "refactor" is a valid commit type in commitizen, alongside with "perf", "test", "style" and "docs".
https://raw.githubusercontent.com/commitizen/cz-cli/master/meta/screenshots/add-commit.png

Using "refactor" displays the error in the title, when I use the latest version of git-pre.
![error](https://cloud.githubusercontent.com/assets/2386064/25403569/07bfbaaa-29fd-11e7-80cb-9e4a0a2dfcd3.png)

**Comment by bahmutov** [comment]
@meszaros-lajos-gyorgy I wrote simple commit message to avoid all the extra "refactor", "test", "WIP", etc words. Instead it is either "major/feat/fix" and everything else is "chore". It is meant to be a subset of conventional commit message

**Comment by meszaros-lajos-gyorgy** [comment]
Ah, okay, now I understand it. Thank you for the info.
