### ISSUE TITLE
Wizard seems to fail on node 8?

### ISSUE THREAD

**Issue by tunnckoCore** [bahmutov/simple-commit-message#13]
Hey! Great modules by you! :)

But i feel this fails from node 8

```
/usr/bin/env: ‘node --harmony’: No such file or directory
```

if manually edit the bin file and remove the `--harmony` flag it works. Strange.

**Comment by bahmutov** [comment]
Hmm probably time to retire --harmony flag!

**Comment by tunnckoCore** [comment]
Yea, absolutely. I'm thinking to drop everything, finally :D

**Comment by tunnckoCore** [comment]
Great! :)
