### ISSUE TITLE
Vulnerable `debug` package

### ISSUE THREAD

**Issue by tunnckoCore** [bahmutov/simple-commit-message#20]
Hey there! :wave: 

I use this package in few places, and in one of them NSP reports that `debug` is older version that has ReDDoS vulnerability.

I am seeing that here is no `debug` as dependency but for some reason the NSP report mention that package, so.. don't know.

https://nodesecurity.io/orgs/tunnckocore-dev/projects/b8ccbfa6-282e-4360-aee5-1497dc059e6b/4

Probably some of your deps uses old debug? Don't know. How can we fix such issues? Probably to install `debug` in my package temporary?

**Comment by charlike** [comment]
I think I found the problem, using `snyk`.

```
Introduced through: hela-config-tunnckocore@tunnckocore/hela-config-tunnckocore#e2afdc295f22c8a5d7dee02fbdf97de60908bfc2 › simple-commit-message@3.3.1 › ggit@1.23.1 › debug@2.6.8 
```

So, the problem is in the `ggit` :)

**Comment by bahmutov** [comment]
is this still a problem? I upgraded all dependencies

**Comment by olstenlarck** [comment]
Not sure. Can't check soon. Probably next week.

You can assign me for reminder.

**Comment by JorritSalverda** [comment]
`npm audit` raises this package to have vulnerable dependencies.

It has a dependency on a version of `inquirer-confirm` that has vulnerabilities because it depends on a vulnerable version of `lodash`. The most recent version of `inquirer-confirm` should probably fix this. You can confirm by running `npm audit` after updating your dependencies.

**Comment by tujoworker** [comment]
yeah, the `lodash` version needs to be updated. But it looks like its a sub dependency:

- `simple-commit-message > ggit > lodash`
- `simple-commit-message > inquirer-confirm > inquirer > lodash`

**Comment by rbardini** [comment]
I opened PR #22 upgrading all dependencies to their latest versions, which should fix `npm audit` security vulnerabilities.

@bahmutov could you please have a look at it?
