### ISSUE TITLE
Postinstall script interferes with semantic-release config

### ISSUE THREAD

**Issue by DanielHabenicht** [bahmutov/simple-commit-message#23]
Hi, I had a really annoying debug session :/

If installing `simple-commit-message` with `semantic-release` and configuring `semantic-release` in a `.releaserc` file the post-install script of this plugin modifies the `package.json` file each time I am doing an npm install (which is every build, as it thinks there is no release configured).
The problem now is that the release config in the `package.json` takes precedence over the `.releaserc` config and in this way uses the standard configuration every build. 

In order to solve this problem there are multiple ways: 

1. (My favorite) Remove the Postinstall script. 
   - Just provide a configuration example in the README.md as every other plugin or package. 
   - Adding a `"release"` option isn't that hard. (Maybe I can refactor the `postinstall` script into a cmd command, so it is still easy to install) 

2. Make it agnostic to `.releaserc` files. 
   - Maybe there are some other config formats I or We couldn't think of, than we will start over again. 

3. At least provide a Environment variable to not execute the postinstall script. 

Please choose one of the above actions and I will try my best to provide a PR for it. Thanks!

**Comment by DanielHabenicht** [comment]
@bahmutov Just tripped over this issue again. Can you provide some input to the question of my issue? 
I would be happy to provide a PR.

**Comment by yurist38** [comment]
Just spent around two hours trying to understand what's going on... Fixed it by moving the config from .releaserc to package.json. Wanted to open an issue but realized that it's here already. So, exactly the same case. When CI executes `npm ci` then `simple-commit-message` adds the "release" section to package.json. When the section exists in package.json `semantic-release` seems to ignore `.releaserc` file. Please let me know if you need more details on this, it's still fresh in my and CI's memories...

**Comment by rbardini** [comment]
I took the liberty to open a PR removing the `postinstall` script in #60, as I've also faced this issue many times and find the current behavior a bit harmful.
