### ISSUE TITLE
Support for Uppercased and all oTHeR-cased prefixes?

### ISSUE THREAD

**Issue by yurist38** [bahmutov/simple-commit-message#67]
Hello! We're using the plugin in our projects and noticed that sometimes it's not triggering a release because the prefix is not lowercased. Did you consider supporting `MAJOR:`, `Major:` and `MaJoR:` kinds of cases? I think it should be a small thing to implement. I'm actually a bit surprised that nobody asked about that before (as far as I can see)... Please let me know about your opinion on this topic. Thank you!

**Comment by bahmutov** [comment]
Hmm no one asked about it, I’m open to a pull request if you want to implement it

**Comment by yurist38** [comment]
That would be amazing, thank you very much! We've bumped into this several times already 😄

**Comment by yurist38** [comment]
I've realized now that I misunderstood your message at first. Though that you'll make the change. I can try to implement it, sure. Will take a look at the code tomorrow...

**Comment by bahmutov** [comment]
Fixed in https://github.com/bahmutov/simple-commit-message/pull/68
